version: '2'
services:
  redis:
    image: sameersbn/redis:latest
    container_name: gitlab-redis
    restart: always
    networks:
      - back
    volumes:
      - redis:/var/lib/redis

  postgresql:
    image: sameersbn/postgresql:9.6-2
    container_name: gitlab-postgresql
    restart: always
    networks:
      - back
    volumes:
      - postgres:/var/lib/postgresql
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_EXTENSION=pg_trgm

  gitlab:
    image: sameersbn/gitlab:8.16.5
    container_name: gitlab
    restart: always
    networks:
      - back
      - front
    depends_on:
      - redis
      - postgresql
    ports:
      - "10022:22"
    volumes:
      - gitlab:/home/git/data
    environment:
      - VIRTUAL_HOST=${GITLAB_VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${GITLAB_VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}

      - DB_ADAPTER=postgresql
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}

      - REDIS_HOST=redis
      - REDIS_PORT=6379

      - GITLAB_TIMEZONE=Paris

      - GITLAB_HTTPS=true
      - SSL_SELF_SIGNED=false

      - GITLAB_HOST=${GITLAB_VIRTUAL_HOST}
      - GITLAB_PORT=443
      - GITLAB_SSH_PORT=10022
      - GITLAB_SECRETS_DB_KEY_BASE=long-and-random-alphanumeric-string

      - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
      - GITLAB_NOTIFY_PUSHER=false

      - GITLAB_BACKUP_SCHEDULE=daily
      - GITLAB_BACKUP_TIME=01:00

      - SMTP_ENABLED=true
      - SMTP_DOMAIN=${SMTP_DOMAIN}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}

      - IMAP_ENABLED=true
      - IMAP_HOST=${IMAP_HOST}
      - IMAP_USER=${IMAP_USER}
      - IMAP_PASS=${IMAP_PASS}

volumes:
  redis:
  postgres:
  gitlab:

networks:
  back:
  front:
    external:
      name: proxy_front
